### ISSUE TITLE
Add White Line Detection

### ISSUE THREAD

**Issue by andyblarblar** [iscumd/KiloOhm#4]
Port white_line_detection from ROS1 Ohm. That node doesn't actually work right now, but should be easy to convert to ROS2 at least. We should make it into it's own unique repo, to be used modularly with other bots.

**Comment by JordanKra** [comment]
Got it to build on foxy with some deprecation warnings so I'm gonna close this

**Comment by andyblarblar** [comment]
Im gonna keep this open until we have it full working, so that requirement is tracked on the project

**Comment by andyblarblar** [comment]
Still keeping this open, but an update for documentations sake.

WLD is currently ported, and outputing points sucessfully in sim with reasonable accuracy. In addition, we added these points to the main cloud in sensor_processor.

WLD now needs to be tested in sim to ensure it is working, then cleaned up a tiny bit so we can let the repo sit without active work for a little. The priority after that is getting the physical flir set up, and then adjusting wld for it. This will be tracked in its own issue.

**Comment by andyblarblar** [comment]
We've configured wld to work at least a little irl. It definitly needs refining, but is otherwise complete as a MVP.
