### ISSUE TITLE
Move to galactic

### ISSUE THREAD

**Issue by andyblarblar** [iscumd/KiloOhm#8]
We're moving to galactic before anything else to avoid the bugs that foxy has.

**Comment by dcutting133** [comment]
Just gonna tag here that if anyone is testing with ROS2 Rolling there are some packages that we use that haven't been properly pushed to the ros buildfarm. So, to get it working there you need to manually clone the Git project.

No problem with Galactic though!

**Comment by andyblarblar** [comment]
Pretty sure everyone is just using Galactic. Rn pretty much everything has been ported by Avery last night, except for some strange nav crashes, so it looks like our dependancies are fine.
